spring.application.name=microcrm

app.cors.allowed-origins=http://localhost:4200,http://localhost:80,https://localhost

opensearch.host=${OPENSEARCH_HOST:localhost}
opensearch.port=${OPENSEARCH_PORT:9200}
opensearch.username=${OPENSEARCH_USERNAME:admin}
opensearch.password=${OPENSEARCH_PASSWORD:}
opensearch.index.defects=microcrm-defects
opensearch.enabled=${OPENSEARCH_ENABLED:true}
